### ISSUE TITLE
QA_Representation of Integers and their Arithmetic_experiment_overflow

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/computer-organization-responsive-lab#4]
Defect Description :
In the experiment section, when we select two values which give a result of "Overflow" - in original experiment the animation for the output is different. 

Actual Result :
In the experiment section, when we select two values which give a result of "Overflow" - in original experiment the animation for the output is different. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:

![qa_co_i005 a](https://user-images.githubusercontent.com/13479177/34100836-c2de58de-e409-11e7-84b2-a5854816a3ec.png)
![qa_co_i005 b](https://user-images.githubusercontent.com/13479177/34100837-c3209640-e409-11e7-8006-fc6a7e07e58b.png)

**Comment by nikhil3435** [comment]
lalit sir approved the issue that overflow can be diplayed in the result table

**Comment by BSravanthi** [comment]
Closed
